### ISSUE TITLE
Users are not able to see one another

### ISSUE THREAD

**Issue by emilyrn18** [SamyCoder/theArtMetaverse#20]
There is a bug that prevents users from seeing each other in the scene.

**Comment by SamyCoder** [comment]
Now we can see the other avatar in the metaverse. 
Still needs: 
- Cannot see oneself
- Avatars changing not working 
- Also, position that the avatars are being places are weird.
- I believe only one other avatar is visible. Check visibility with multiple avatars.

**Comment by emilyrn18** [comment]
I thought we fixed this? Can we close this?
